language: java
sudo: required
jdk:
- openjdk8
services:
- docker

before_install:
- sudo echo "deb http://ftp.de.debian.org/debian jessie-backports main" | sudo tee --append /etc/apt/sources.list
- sudo apt-key adv --keyserver pgpkeys.mit.edu --recv-key 8B48AD6246925553
- sudo apt-key adv --keyserver pgpkeys.mit.edu --recv-key 7638D0442B90D010
- sudo apt-get update -qq
- sudo apt-get -y install git zip avahi-daemon wget
- sudo apt-get -y -t jessie-backports  openjdk-8-jre-headless ca-certificates-java

install:
- wget -O /data/BuildTools.jar https://hub.spigotmc.org/jenkins/job/BuildTools/lastSuccessfulBuild/artifact/target/BuildTools.jar 
- java -jar BuildTools.jar
- docker build -t ekellener/minecraft-arm:12t -f Dockerfile.arm .

