language: java
sudo: required
jdk:
- openjdk8
services:
- docker

before_install:
- sudo apt-get install -y  git wget openjdk-8-jre-headless ca-certificates-java

install:
- wget -O BuildTools.jar https://hub.spigotmc.org/jenkins/job/BuildTools/lastSuccessfulBuild/artifact/target/BuildTools.jar 
- java -jar BuildTools.jar
- docker build -t ekellener/minecraft-arm:12t -f Dockerfile.arm .
script:
- docker build -t ekellener/minecraft-arm:12t -f Dockerfile.arm .
- docker build -t ekellener/minecraft-amd64:12t -f Dockerfile.amd64 .
